version: '3.8'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.app.dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 111
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: karinaabdu6@gmail.com
      SPRING_MAIL_PASSWORD: pwkotchqzliqgsco
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
    depends_on:
      - db
  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 111
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/course.sql